const actionTypes = {
    // AUTH
    LOGIN_SUCESS: 'LOGIN_SUCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    STAFF_LOGIN_SUCESS: 'STAFF_LOGIN_SUCESS',
    REGISTER_SUCESS: 'REGISTER_SUCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    CHANGEPASS_SUCESS: 'CHANGEPASS_SUCESS',
    CHANGEPASS_FAIL: 'CHANGEPASS_FAIL',
    MAIL_SUCESS: 'CHANGEPASS_SUCESS',
    MAIL_FAIL: 'CHANGEPASS_FAIL',
    LOGOUT: 'LOGOUT',
    REFRESH_TOKEN: 'REFRESH_TOKEN',

    // USER
        // Customer
    GET_CURRENT: 'GET_CURRENT',
        // Staff
    GET_ALL_STAFF: 'GET_ALL_STAFF',
    // TOUR
    GET_TOURS_RATING: 'GET_TOURS_RATING',
    GET_TOURS_CONDITION: 'GET_TOURS_CONDITION',
    GET_TOUR: 'GET_TOUR',
    GET_TOURS_NAME: 'GET_TOURS_NAME',
    GET_TOURS_STAFF: 'GET_TOURS_STAFF',
    // ORDER
    GET_ORDER_OF_TOUR: 'GET_ORDER_OF_TOUR',
    GET_ORDER_OF_CUSTOMER: 'GET_ORDER_OF_CUSTOMER',
    // PLACE
    GET_PLACES: 'GET_PLACES',
    // FEEDACK
    GET_FEEDBACK_OF_TOURTYPE: 'GET_FEEDBACK_OF_TOURTYPE',
    COUNT_ORDER_TOURTYPE: 'COUNT_ORDER_TOURTYPE',
    // REQUEST
    GET_ALL_REQUESTS: 'GET_ALL_REQUESTS',
    GET_REQUEST: 'GET_REQUEST',
    GET_REQUESTS_STAFF: 'GET_REQUESTS_STAFF',
    REQUEST_ADD: 'REQUEST_ADD'
}
export default actionTypes