# Generated by Django 4.2.1 on 2024-01-20 05:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("phone_no", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "manager_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("pay_method", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("phone_no", models.CharField(max_length=10, unique=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(max_length=200)),
                ("ticker_num", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "place_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("province", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("tour_ID", models.AutoField(primary_key=True, serialize=False)),
                ("departure", models.CharField(max_length=50)),
                (
                    "vehicle",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=30), max_length=360, size=10
                    ),
                ),
                ("seat_num", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("isActive", models.BooleanField()),
                ("starting_date", models.DateField()),
                ("bookingDeadline", models.DateField()),
                ("day_num", models.IntegerField()),
                ("night_num", models.IntegerField()),
                ("note", models.CharField(max_length=100)),
                ("places", models.ManyToManyField(to="mydata.place")),
            ],
        ),
        migrations.CreateModel(
            name="TourService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TService",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=200), max_length=2400, size=10
                    ),
                ),
                ("tour_ID", models.ManyToManyField(to="mydata.tour")),
            ],
        ),
        migrations.CreateModel(
            name="TourSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TSchedule",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=1000), max_length=12000, size=10
                    ),
                ),
                (
                    "tour_ID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.tour"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff_add_Order_of_Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.order"
                    ),
                ),
                (
                    "staff_ID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mydata.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(max_length=10)),
                ("dateOfBirth", models.DateField()),
                ("isActive", models.BooleanField()),
                ("gender", models.CharField(max_length=1)),
                ("lastName", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=100)),
                ("encryp_pass", models.CharField(max_length=50)),
                (
                    "managerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.manager"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "request_ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reply", models.CharField(max_length=200)),
                ("typ", models.CharField(max_length=30)),
                (
                    "manager_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.manager"
                    ),
                ),
                (
                    "staff_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.staff"
                    ),
                ),
                (
                    "tour_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.tour"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="uploads/%Y/%m")),
                (
                    "place_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.place"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="staff_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mydata.staff"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tour_ID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mydata.tour",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_ID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mydata.customer",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "feedback_ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "ratings",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1),
                            django.core.validators.MaxValueValidator(limit_value=5),
                        ]
                    ),
                ),
                ("reviews", models.CharField(blank=True, max_length=200)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "tour_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.tour"
                    ),
                ),
                (
                    "user_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mydata.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_draft", models.JSONField()),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.request"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer_views_Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.place"
                    ),
                ),
                (
                    "user_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mydata.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CancelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.request"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure", models.CharField(max_length=50)),
                (
                    "vehicle",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=30), max_length=360, size=10
                    ),
                ),
                ("seat_num", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("isActive", models.BooleanField()),
                ("starting_date", models.DateField()),
                ("bookingDeadline", models.DateField()),
                ("day_num", models.IntegerField()),
                ("night_num", models.IntegerField()),
                ("note", models.CharField(max_length=100)),
                ("places", models.ManyToManyField(to="mydata.place")),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydata.request"
                    ),
                ),
            ],
        ),
    ]
