const actionTypes = {
    LOGIN_SUCESS: 'LOGIN_SUCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCESS: 'REGISTER_SUCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',

    // USER
    GET_CURRENT: 'GET_CURRENT',

    // TOUR
    GET_TOURS: 'GET_TOURS',
    GET_TOURS_LIMIT: 'GET_TOURS_LIMIT'
}
export default actionTypes