const actionTypes = {
    LOGIN_SUCESS: 'LOGIN_SUCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCESS: 'REGISTER_SUCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    CHANGEPASS_SUCESS: 'CHANGEPASS_SUCESS',
    CHANGEPASS_FAIL: 'CHANGEPASS_FAIL',
    MAIL_SUCESS: 'CHANGEPASS_SUCESS',
    MAIL_FAIL: 'CHANGEPASS_FAIL',
    LOGOUT: 'LOGOUT',

    // USER
    GET_CURRENT: 'GET_CURRENT',

    // TOUR
    GET_TOURS_RATING: 'GET_TOURS_RATING',
    GET_TOURS_CONDITION: 'GET_TOURS_CONDITION',
    GET_TOUR: 'GET_TOUR',
    GET_TOURS_NAME: 'GET_TOURS_NAME',
    GET_TOURS_STAFF: 'GET_TOURS_STAFF',
    // ORDER
    GET_ORDER_OF_TOUR: 'GET_ORDER_OF_TOUR',
}
export default actionTypes